# Generated by Django 2.1.1 on 2018-09-30 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('started_from', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('ip', models.GenericIPAddressField(blank=True, default='soubhagya-Inspiron-3542', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('framework_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('framework_name', models.CharField(max_length=255)),
                ('framework_logo', models.FileField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('latest_build_on', models.DateTimeField(auto_now_add=True)),
                ('latest_version', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255)),
                ('language_logo', models.FileField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('latest_build_on', models.DateTimeField(auto_now_add=True)),
                ('latest_version', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='serializers.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('technology_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('technology_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.ManyToManyField(related_name='technology', to='serializers.Language')),
            ],
        ),
        migrations.AddField(
            model_name='frameworks',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='serializers.Language'),
        ),
    ]
