# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default=b'wishbook', null=True),
        ),
    ]
